#Mon 15 Oct 10:01:34 BST 2018
export BRANCH_NAME=
export OSE_VERSIONS=3.9
export CHEF_VERSION=
export CHEF_YUM_COOKBOOK_VERSION=
export CHEF_SELINUX_COOKBOOK_VERSION=
export CHEF_COMPAT_RESOURCE_COOKBOOK_VERSION=
export CHEF_INJECT_COMPAT_RESOURCE_COOKBOOK_VERSION=
export CHEF_IPTABLES_COOKBOOK_VERSION=
export CHEF_DEPLOY_METHODS=solo
export SHUTIT_CLUSTER_CONFIGS=test_single_node
export SHUTIT_INTERACTIVE=
export DO_ADHOC_UNINSTALL=
export DO_ADHOC_RESET=
export DO_VAULT=
export DO_ISTIO=
export DO_CRD=
export DO_CONTROLLER=true
export UPGRADE_13_14=
export UPGRADE_14_15=
export UPGRADE_15_36=
export UPGRADE_36_37=
export CHEF_DEPLOY_CONTAINERIZED=
./run_tests.sh
